// import './globals.css'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import 'react-toastify/dist/ReactToastify.css';
// import '@styles/app.css';
import Header from '@/components/layout/header';
import { ThemeProvider } from 'next-themes';
import ThemeSwitcher from '@/components/layout/themeSwitcher';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html suppressHydrationWarning>
      <body className={inter.className}>
        <Header />
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem={true}>
          <ThemeSwitcher />
          <div className='container dark:bg-black'>
            {children}
          </div>
        </ThemeProvider>
        </body>
    </html>
  )
}
